### PR TITLE
DE-1807 add first commit id to branch

### PR DESCRIPTION
**Pull request by robindiddams**
**Description:**
for master branch commits are out of order (which makes sense traversing a tree) but the chronological order is important, some things need first and last commit, so we added logic to determine the first commit.

### CODE REVIEW

**Review by jhaynie — APPROVED** [review]

**Comment by rblalock** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ripsrc/branches2/process.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/ripsrc/ripsrc/pullRequest?prid=4564128&bid=15345141)

**Comment by xzandrew** [comment]
This PR broke 6 branch related unit tests, because they check object that now has a new field.

To see them:
`go test github.com/pinpt/ripsrc/...`

**Comment by xzandrew** [comment]
@Robindiddams Do we need to fix the order of commits in the Commits array as well? Or it's not needed at least right now.

**Comment by jhaynie** [comment]
we really just need to know the first commit and the merge commit. right @Robindiddams ?

**Pull request merged**
