### PR TITLE
Remove signed field from commits

### PR DESCRIPTION
**Pull request by josecordaz**
- First draft to remove signed field from commits. It is not being used.

### CODE REVIEW

**Review by jhaynie — APPROVED** [review]
LGTM

**Comment by rblalock** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ripsrc/commitmeta/commitmeta.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Pinpoint/ripsrc/pullRequest?prid=4642184&bid=15550272)

**Review by xzandrew — CHANGES_REQUESTED** [review]
Need to remove the field from Commit struct as well.

**Comment by rblalock** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ripsrc/commitmeta/commitmeta.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Pinpoint/ripsrc/pullRequest?prid=4642184&bid=15550272)

**Comment by xzandrew** [comment]
This has compile errors in tests:

```
go test github.com/pinpt/ripsrc/...
# github.com/pinpt/ripsrc/ripsrc/commitmeta/tests [github.com/pinpt/ripsrc/ripsrc/commitmeta/tes
ts.test]
ripsrc/commitmeta/tests/basic_test.go:46:3: unknown field 'Signed' in struct literal of type com
mitmeta.Commit
ripsrc/commitmeta/tests/basic_test.go:62:3: unknown field 'Signed' in struct literal of type com
mitmeta.Commit
ripsrc/commitmeta/tests/merge_basic_test.go:35:3: unknown field 'Signed' in struct literal of ty
pe commitmeta.Commit
ripsrc/commitmeta/tests/merge_basic_test.go:59:3: unknown field 'Signed' in struct literal of ty
pe commitmeta.Commit
ripsrc/commitmeta/tests/merge_basic_test.go:83:3: unknown field 'Signed' in struct literal of ty
pe commitmeta.Commit
ripsrc/commitmeta/tests/merge_basic_test.go:107:3: unknown field 'Signed' in struct literal of t
ype commitmeta.Commit```

**Comment by rblalock** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ ripsrc/commitmeta/commitmeta.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Pinpoint/ripsrc/pullRequest?prid=4642184&bid=15550272)

**Pull request merged**
